#!/usr/bin/env python3
"""Evaluate side-specific post-cooldown rearm with paired DR contrasts.

The candidate policy selects ``continue_block_until_recovery`` only when the
frozen decision-time adverse state is active; otherwise it falls back to
``baseline_rearm``.  Development uses chronological cross-fitting.  Later
panels fit nuisance models only on the frozen Development panel.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from dataclasses import asdict
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from models.audit.experiment_manifest import git_workspace_identity
from models.audit.experiment_scorecard import score_action_family_result
from research.families.f09_inventory_lifecycle_action_uplift.audit.local_action_ope_report import (
    _paired_action_contrast,
    _write_action_contrast,
)
from research.families.f09_inventory_lifecycle_action_uplift.audit.offline_policy_evaluation import (
    OPEConfig,
    evaluate_fixed_holdout_policy,
    evaluate_offline_policy,
    write_outputs,
)
from research.families.f09_inventory_lifecycle_action_uplift.audit.state_conditioned_rearm_randomized import (
    FAMILY_IDS,
    validate_panel,
)
from models.replay_policies import StateConditionedRearmSpec

ROOT = Path(__file__).resolve().parents[4]
SCHEMA_VERSION = "state_conditioned_rearm_ope.v1"
BASELINE_ACTION = "baseline_rearm"
CANDIDATE_ACTION = "continue_block_until_recovery"
TAIL_THRESHOLD_USDC = -5.0

FEATURES = (
    "inventory_ratio",
    "inventory_lifecycle_age_s",
    "inventory_lifecycle_max_abs_qty_so_far",
    "inventory_lifecycle_pnl_so_far",
    "inventory_lifecycle_adverse_excursion_so_far",
    "inventory_lifecycle_mae_so_far",
    "inventory_lifecycle_exposure_increasing_fills_so_far",
    "inventory_lifecycle_reducing_fills_so_far",
    "inventory_lifecycle_add_count_so_far",
    "toxicity",
    "markout_ema",
    "weighted_mid_proxy_shift_bps",
    "l2_quote_flip_rate",
    "l2_book_refresh_ratio",
    "l2_book_cancel_ratio",
    "l2_near_depth_total",
    "path_elapsed_ms",
    "path_book_age_ms",
    "path_l2_snapshot_count",
    "path_trade_count",
    "shock_adverse_flow_imbalance_1s",
    "shock_adverse_flow_imbalance_5s",
    "shock_adverse_flow_imbalance_since_fill",
    "shock_adverse_qty_to_depth_5s",
    "shock_adverse_qty_to_depth_since_fill",
    "shock_adverse_move_bps",
    "shock_time_to_extreme_ms",
    "refill_depletion_ratio",
    "refill_recovery_ratio",
    "refill_current_vs_start_ratio",
    "refill_half_life_ms",
    "refill_half_life_observed",
    "recovery_current_adverse_bps",
    "recovery_from_extreme_bps",
    "recovery_price_ratio",
    "recovery_microprice_current_adverse_bps",
    "recovery_microprice_ratio",
    "quote_distance_ticks",
    "exact_l2_spread_bps",
)

OUTCOMES = (
    "reward",
    "inventory_lifecycle_cost_avoidance",
    "negative_terminal_mtm",
    "development_q10_shortfall",
    "inventory_lifecycle_mae_avoidance",
    "tail_avoidance_5usdc",
    "repair_30m",
    "repair_time_avoidance_s",
    "censoring_avoidance",
    "duration_avoidance_30m",
    "intervention_fill_avoidance",
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _read_metadata(panel_path: Path) -> tuple[Path, dict[str, Any]]:
    raw = str(panel_path)
    metadata_path = Path(
        raw[: -len(".action_panel.csv")] + ".metadata.json"
        if raw.endswith(".action_panel.csv")
        else str(panel_path.with_suffix(".metadata.json"))
    )
    if not metadata_path.is_file():
        raise FileNotFoundError(f"panel metadata is missing: {metadata_path}")
    return metadata_path, json.loads(metadata_path.read_text(encoding="utf-8"))


def _validate_identity(
    panel: pd.DataFrame,
    metadata: dict[str, Any],
    *,
    side: str,
    panel_role: str,
    family_id: str,
    action_family: str,
    family_spec: dict[str, Any] | None = None,
) -> None:
    validate_panel(panel, side=side)
    if metadata.get("family_id") != family_id:
        raise ValueError("panel metadata belongs to another family")
    if metadata.get("panel_role") != panel_role:
        raise ValueError("panel metadata role differs from requested evaluation")
    if metadata.get("action_family") != action_family:
        raise ValueError("panel was not generated by the rearm runner")
    for invariant in (
        "reducing_side_modified",
        "order_size_modified",
        "inventory_limit_modified",
        "external_reference_used",
    ):
        if bool(metadata.get(invariant)):
            raise ValueError(f"frozen invariant was violated: {invariant}")
    if not bool(metadata.get("one_intervention_per_inventory_lifecycle")):
        raise ValueError("panel is not one-intervention-per-inventory_lifecycle")
    if not math.isclose(
        float(metadata.get("baseline_fill_cooldown_s", 0.0)),
        85.0,
        abs_tol=1e-12,
    ):
        raise ValueError("panel does not use the frozen 85-second control")
    if family_spec is not None:
        baseline = family_spec.get("baseline") or {}
        identity_pairs = {
            "config_sha256": metadata.get("config_sha256"),
            "queue_sha256": metadata.get("queue_artifact_sha256"),
            "latency_sha256": metadata.get("telemetry_sha256"),
        }
        for key, actual in identity_pairs.items():
            if str(actual or "") != str(baseline.get(key, "")):
                raise ValueError(f"panel baseline identity differs for {key}")
        expected_spec_sha = str(metadata.get("family_spec_sha256", ""))
        spec_path = Path(str(metadata.get("family_spec_path", ""))).resolve()
        if not spec_path.is_file() or _sha256(spec_path) != expected_spec_sha:
            raise ValueError("panel family-spec file identity is invalid")


def _derive_outcomes(frame: pd.DataFrame, *, q10: float) -> pd.DataFrame:
    out = frame.copy()
    reward = pd.to_numeric(out["reward"], errors="coerce")
    inventory_lifecycle_cost = pd.to_numeric(out["inventory_lifecycle_cost"], errors="coerce")
    terminal = pd.to_numeric(out["terminal_inventory_lifecycle_pnl"], errors="coerce")
    duration = pd.to_numeric(out["decision_to_outcome_s"], errors="coerce")
    closed = pd.to_numeric(out["inventory_lifecycle_closed"], errors="coerce").eq(1)
    fill_count = pd.to_numeric(out["intervention_fill_count"], errors="coerce")
    out["reward"] = reward
    out["inventory_lifecycle_cost_avoidance"] = -inventory_lifecycle_cost
    out["negative_terminal_mtm"] = terminal.clip(upper=0.0)
    out["development_q10_shortfall"] = (terminal - float(q10)).clip(upper=0.0)
    out["inventory_lifecycle_mae_avoidance"] = pd.to_numeric(
        out["inventory_lifecycle_mae"], errors="coerce"
    )
    out["tail_avoidance_5usdc"] = -(terminal <= TAIL_THRESHOLD_USDC).astype(float)
    out["repair_30m"] = (closed & duration.le(1_800.0)).astype(float)
    repair_time = pd.to_numeric(
        out["time_to_repair_s"], errors="coerce"
    ).clip(lower=0.0, upper=1_800.0)
    out["repair_time_avoidance_s"] = -np.where(
        closed,
        repair_time,
        1_800.0,
    )
    out["censoring_avoidance"] = -pd.to_numeric(
        out["inventory_lifecycle_censored"], errors="coerce"
    ).clip(lower=0.0, upper=1.0)
    out["duration_avoidance_30m"] = -duration.clip(lower=0.0, upper=1_800.0) / 1_800.0
    out["intervention_fill_avoidance"] = -(fill_count > 0).astype(float)
    if not np.isfinite(out[list(OUTCOMES)].to_numpy(dtype=float)).all():
        raise ValueError("derived OPE outcomes contain missing or non-finite values")
    return out


def _candidate_policy(frame: pd.DataFrame) -> pd.Series:
    active = pd.to_numeric(frame["entry_state_active"], errors="coerce").eq(1)
    return pd.Series(
        np.where(active, CANDIDATE_ACTION, BASELINE_ACTION),
        index=frame.index,
        dtype="string",
    )


def _bootstrap_lower(summary: dict[str, Any]) -> float:
    return float(summary["day_cluster_bootstrap"]["uplift_p025"])


def _point(summary: dict[str, Any]) -> float:
    return float(summary["dr_uplift"])


def _run_contrast(
    frame: pd.DataFrame,
    *,
    outcome: str,
    output_prefix: Path,
    scope: str,
    config: OPEConfig,
    training_frame: pd.DataFrame | None,
) -> dict[str, Any]:
    candidate = frame.copy()
    candidate["candidate_action"] = _candidate_policy(candidate)
    baseline = frame.copy()
    baseline["candidate_action"] = BASELINE_ACTION
    if training_frame is None:
        candidate_rows, candidate_folds, candidate_actions, candidate_summary = evaluate_offline_policy(
            candidate,
            feature_names=FEATURES,
            config=OPEConfig(**{**vars(config), "reward_col": outcome}),
        )
        baseline_rows, baseline_folds, baseline_actions, baseline_summary = evaluate_offline_policy(
            baseline,
            feature_names=FEATURES,
            config=OPEConfig(**{**vars(config), "reward_col": outcome}),
        )
    else:
        train_candidate = training_frame.copy()
        train_candidate["candidate_action"] = _candidate_policy(train_candidate)
        train_baseline = training_frame.copy()
        train_baseline["candidate_action"] = BASELINE_ACTION
        candidate_rows, candidate_folds, candidate_actions, candidate_summary = evaluate_fixed_holdout_policy(
            train_candidate,
            candidate,
            feature_names=FEATURES,
            config=OPEConfig(**{**vars(config), "reward_col": outcome}),
        )
        baseline_rows, baseline_folds, baseline_actions, baseline_summary = evaluate_fixed_holdout_policy(
            train_baseline,
            baseline,
            feature_names=FEATURES,
            config=OPEConfig(**{**vars(config), "reward_col": outcome}),
        )
    candidate_paths = write_outputs(
        output_prefix.parent / f"{output_prefix.name}_{scope}_{outcome}_candidate",
        candidate_rows,
        candidate_folds,
        candidate_actions,
        candidate_summary,
    )
    baseline_paths = write_outputs(
        output_prefix.parent / f"{output_prefix.name}_{scope}_{outcome}_baseline",
        baseline_rows,
        baseline_folds,
        baseline_actions,
        baseline_summary,
    )
    contrast_rows, contrast_summary = _paired_action_contrast(
        candidate_rows,
        baseline_rows,
        candidate_action=CANDIDATE_ACTION,
        baseline_action=BASELINE_ACTION,
        candidate_summary=candidate_summary,
        baseline_summary=baseline_summary,
        bootstrap_trials=config.bootstrap_trials,
        random_seed=config.random_seed,
    )
    contrast_paths = _write_action_contrast(
        output_prefix.parent / f"{output_prefix.name}_{scope}_{outcome}",
        contrast_rows,
        contrast_summary,
    )
    return {
        "candidate": candidate_paths,
        "baseline": baseline_paths,
        "contrast": contrast_paths,
        "summary": contrast_summary,
    }


def _build_gate(
    results: dict[str, dict[str, dict[str, Any]]],
    *,
    panel: pd.DataFrame,
    family_spec: dict[str, Any] | None = None,
) -> dict[str, Any]:
    all_scope = results["all_inventory_lifecycles"]
    active_scope = results.get("entry_state_active", {})
    action = panel["action"].astype(str)
    active = pd.to_numeric(panel["entry_state_active"], errors="coerce").eq(1)
    effective_candidate_rows = int((active & action.eq(CANDIDATE_ACTION)).sum())
    active_baseline_rows = int((active & action.eq(BASELINE_ACTION)).sum())
    active_days = int(panel.loc[active, "day"].astype(str).nunique())
    candidate_effective = panel[
        active & action.eq(CANDIDATE_ACTION)
    ]
    multicycle_rate = float(
        (
            pd.to_numeric(candidate_effective["blocked_quote_cycles"], errors="coerce")
            > 1
        ).mean()
    ) if len(candidate_effective) else 0.0
    candidate_rate = float(active.mean())
    baseline = action.eq(BASELINE_ACTION)
    fill_count = pd.to_numeric(
        panel["intervention_fill_count"], errors="coerce"
    ).clip(lower=0.0)
    baseline_fill_events = float(fill_count[baseline].sum())
    blocked_baseline_fill_events = float(fill_count[baseline & active].sum())
    fills_retention = (
        1.0 - blocked_baseline_fill_events / baseline_fill_events
        if baseline_fill_events > 0.0
        else 0.0
    )

    checks = {
        "all_reward_lower_positive": _bootstrap_lower(all_scope["reward"]["summary"]) > 0.0,
        "inventory_lifecycle_cost_lower_nonnegative": _bootstrap_lower(all_scope["inventory_lifecycle_cost_avoidance"]["summary"]) >= 0.0,
        "tail_5usdc_lower_nonnegative": _bootstrap_lower(all_scope["tail_avoidance_5usdc"]["summary"]) >= 0.0,
        "q10_shortfall_lower_nonnegative": _bootstrap_lower(all_scope["development_q10_shortfall"]["summary"]) >= 0.0,
        "negative_terminal_lower_nonnegative": _bootstrap_lower(all_scope["negative_terminal_mtm"]["summary"]) >= 0.0,
        "repair_point_nonnegative": _point(all_scope["repair_30m"]["summary"]) >= 0.0,
        "duration_point_nonnegative": _point(all_scope["duration_avoidance_30m"]["summary"]) >= 0.0,
        "active_action_support": effective_candidate_rows >= 50 and active_baseline_rows >= 50 and active_days >= 10,
        "candidate_is_multicycle": multicycle_rate >= 0.50,
        "reward_daily_positive_rate": float(all_scope["reward"]["summary"]["daily_uplift"]["positive_rate"]) >= 0.55,
        "ope_overlap": all(
            bool(row["summary"]["numerical_contrast_gate_passed"])
            for scope in results.values()
            for row in scope.values()
        ),
    }
    if family_spec is None:
        checks["active_reward_lower_positive"] = bool(active_scope) and (
            _bootstrap_lower(active_scope["reward"]["summary"]) > 0.0
        )
    if family_spec is not None:
        hard_gates = family_spec.get("formal_hard_gates") or {}
        rate_budget = hard_gates.get("candidate_rate") or (0.05, 0.30)
        checks["candidate_rate_budget"] = bool(
            float(rate_budget[0])
            <= candidate_rate
            <= float(rate_budget[1])
        )
        checks["fills_retention"] = bool(
            fills_retention >= float(hard_gates.get("fills_retention", 0.85))
        )
    return {
        "passed": bool(all(checks.values())),
        "checks": checks,
        "support": {
            "rows": int(len(panel)),
            "days": int(panel["day"].astype(str).nunique()),
            "entry_state_rows": int(active.sum()),
            "entry_state_days": active_days,
            "effective_candidate_rows": effective_candidate_rows,
            "active_baseline_rows": active_baseline_rows,
            "candidate_multicycle_rate": multicycle_rate,
            "candidate_rate": candidate_rate,
            "baseline_fill_events": baseline_fill_events,
            "blocked_baseline_fill_events": blocked_baseline_fill_events,
            "fills_retention": fills_retention,
            "active_scope_ope_status": (
                "estimated"
                if active_scope
                else "support_only; deployment uplift is estimated on all inventory_lifecycles"
            ),
        },
    }


def _scorecard_metric(
    result: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    summary = result["summary"]
    bootstrap = summary["day_cluster_bootstrap"]
    return {
        "uplift": float(summary["dr_uplift"]),
        "interval": {
            "p025": float(bootstrap["uplift_p025"]),
            "p975": float(bootstrap["uplift_p975"]),
        },
        "daily_positive_rate": float(
            summary["daily_uplift"]["positive_rate"]
        ),
    }


def _write_scorecard(
    *,
    family_id: str,
    family_spec_path: Path,
    family_spec: dict[str, Any],
    panel_role: str,
    panel_path: Path,
    gate: dict[str, Any],
    results: dict[str, dict[str, dict[str, Any]]],
    output_prefix: Path,
) -> tuple[Path, dict[str, Any]]:
    all_scope = results["all_inventory_lifecycles"]
    reward_summary = all_scope["reward"]["summary"]
    failed_checks = [
        name for name, passed in gate["checks"].items() if not bool(passed)
    ]
    score_result = {
        "schema_version": "recovery_event_rearm_result.v1",
        "family_id": family_id,
        "family_spec": {
            "path": str(family_spec_path),
            "sha256": _sha256(family_spec_path),
        },
        f"{panel_role}_panel": {
            "path": str(panel_path),
            "sha256": _sha256(panel_path),
        },
        f"{panel_role}_gate_passed": bool(gate["passed"]),
        f"{panel_role}_failures": failed_checks,
        "status": (
            f"{panel_role}_passed"
            if gate["passed"]
            else f"{panel_role}_failed"
        ),
        panel_role: {
            "reward": _scorecard_metric(all_scope["reward"]),
            "negative_terminal_protection": _scorecard_metric(
                all_scope["negative_terminal_mtm"]
            ),
            "development_q10_shortfall_protection": _scorecard_metric(
                all_scope["development_q10_shortfall"]
            ),
            "inventory_lifecycle_mae_avoidance": _scorecard_metric(
                all_scope["inventory_lifecycle_mae_avoidance"]
            ),
            "repair_event": _scorecard_metric(all_scope["repair_30m"]),
            "restricted_time_to_repair": _scorecard_metric(
                all_scope["repair_time_avoidance_s"]
            ),
            "day_end_censoring_avoidance": _scorecard_metric(
                all_scope["censoring_avoidance"]
            ),
            "activity": {
                "fills_retention": float(
                    gate["support"]["fills_retention"]
                )
            },
            "support": {
                "oof_rows": int(reward_summary["rows"]),
                "oof_days": int(reward_summary["days"]),
                "policy_ess": float(
                    reward_summary["candidate_effective_sample_size"]
                ),
                "min_behavior_propensity": 0.5,
                "unsupported_candidate_rows": 0,
                "overlap_violations": 0,
                "candidate_rate": float(gate["support"]["candidate_rate"]),
                "failures": [],
            },
        },
    }
    scorecard = score_action_family_result(
        score_result,
        family_spec,
        panel_role=panel_role,
        profile_id="action_defense_v1",
    )
    path = output_prefix.with_suffix(".scorecard.json")
    path.write_text(
        json.dumps(scorecard, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return path, scorecard


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--side", choices=("SELL", "BUY"), default="SELL")
    parser.add_argument("--panel-role", choices=("development", "validation", "sealed_holdout"), required=True)
    parser.add_argument("--panel", type=Path, required=True)
    parser.add_argument("--panel-metadata", type=Path, default=None)
    parser.add_argument("--development-panel", type=Path, default=None)
    parser.add_argument("--development-metadata", type=Path, default=None)
    parser.add_argument("--frozen-policy", type=Path, default=None)
    parser.add_argument("--frozen-family-spec", type=Path, default=None)
    parser.add_argument("--output-prefix", type=Path, required=True)
    parser.add_argument("--min-train-days", type=int, default=30)
    parser.add_argument("--test-days", type=int, default=5)
    parser.add_argument("--embargo-days", type=int, default=1)
    parser.add_argument("--min-action-rows", type=int, default=50)
    parser.add_argument("--min-effective-sample-size", type=float, default=100.0)
    parser.add_argument("--bootstrap-trials", type=int, default=2_000)
    parser.add_argument("--random-seed", type=int, default=20260722)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    side = str(args.side).upper()
    family_spec_path = (
        args.frozen_family_spec.expanduser().resolve()
        if args.frozen_family_spec is not None
        else None
    )
    family_spec: dict[str, Any] | None = None
    if family_spec_path is not None:
        family_spec = json.loads(family_spec_path.read_text(encoding="utf-8"))
        if family_spec.get("schema_version") != "recovery_event_rearm_family.v1":
            raise ValueError("unsupported recovery-event family spec")
        if str(family_spec.get("side", "")).upper() != side:
            raise ValueError("family spec side differs from --side")
        family_id = str(family_spec["family_id"])
        action_family = "recovery_event_rearm"
    else:
        family_id = FAMILY_IDS[side]
        action_family = "state_conditioned_rearm"
    panel_path = args.panel.expanduser().resolve()
    panel = pd.read_csv(panel_path)
    if args.panel_metadata is None:
        metadata_path, metadata = _read_metadata(panel_path)
    else:
        metadata_path = args.panel_metadata.expanduser().resolve()
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    _validate_identity(
        panel,
        metadata,
        side=side,
        panel_role=args.panel_role,
        family_id=family_id,
        action_family=action_family,
        family_spec=family_spec,
    )

    training: pd.DataFrame | None = None
    training_metadata_path: Path | None = None
    policy_path: Path | None = None
    if args.panel_role == "development":
        q10 = float(pd.to_numeric(panel["terminal_inventory_lifecycle_pnl"], errors="coerce").quantile(0.10))
    else:
        if args.development_panel is None or args.frozen_policy is None:
            raise ValueError("later evidence requires --development-panel and --frozen-policy")
        training_path = args.development_panel.expanduser().resolve()
        training = pd.read_csv(training_path)
        if args.development_metadata is None:
            training_metadata_path, training_metadata = _read_metadata(training_path)
        else:
            training_metadata_path = args.development_metadata.expanduser().resolve()
            training_metadata = json.loads(training_metadata_path.read_text(encoding="utf-8"))
        _validate_identity(
            training,
            training_metadata,
            side=side,
            panel_role="development",
            family_id=family_id,
            action_family=action_family,
            family_spec=family_spec,
        )
        policy_path = args.frozen_policy.expanduser().resolve()
        policy = json.loads(policy_path.read_text(encoding="utf-8"))
        if policy.get("family_id") != family_id:
            raise ValueError("frozen policy belongs to another family")
        if policy.get("development_panel_sha256") != _sha256(training_path):
            raise ValueError("frozen policy is not bound to this Development panel")
        q10 = float(policy["development_q10_usdc"])

    panel = _derive_outcomes(panel, q10=q10)
    if training is not None:
        training = _derive_outcomes(training, q10=q10)
    config = OPEConfig(
        split_mode="chronological",
        min_train_days=int(args.min_train_days),
        test_days=int(args.test_days),
        embargo_days=int(args.embargo_days),
        min_train_rows=max(300, int(args.min_action_rows) * 4),
        min_action_rows=int(args.min_action_rows),
        min_effective_sample_size=float(args.min_effective_sample_size),
        bootstrap_trials=int(args.bootstrap_trials),
        random_seed=int(args.random_seed),
    )
    output_prefix = args.output_prefix.expanduser().resolve()
    output_prefix.parent.mkdir(parents=True, exist_ok=True)
    scopes = {"all_inventory_lifecycles": panel}
    active_panel = panel[pd.to_numeric(panel["entry_state_active"], errors="coerce").eq(1)].copy()
    active_counts = active_panel["action"].astype(str).value_counts()
    active_development_supported = bool(
        active_panel["day"].astype(str).nunique()
        >= int(args.min_train_days) + int(args.embargo_days) + 1
        and all(
            int(active_counts.get(action, 0)) >= int(args.min_action_rows)
            for action in (BASELINE_ACTION, CANDIDATE_ACTION)
        )
    )
    # The recovery-event policy differs from baseline on only 5-30% of rows.
    # Its randomized active subgroup has enough total support for the action
    # gate, but not enough rows per chronological fold for a separate nuisance
    # model. Estimate the deployable policy value on all inventory_lifecycles; retain the
    # active subgroup as support diagnostics instead of weakening fold gates.
    estimate_active_scope = family_spec is None and (
        args.panel_role != "development" or active_development_supported
    )
    if estimate_active_scope and not active_panel.empty:
        scopes["entry_state_active"] = active_panel
    training_scopes: dict[str, pd.DataFrame] = {}
    if training is not None:
        training_scopes["all_inventory_lifecycles"] = training
        if family_spec is None:
            training_scopes["entry_state_active"] = training[
                pd.to_numeric(training["entry_state_active"], errors="coerce").eq(1)
            ].copy()

    results: dict[str, dict[str, dict[str, Any]]] = {}
    for scope, scoped in scopes.items():
        if scoped["day"].astype(str).nunique() < 2:
            continue
        results[scope] = {}
        for outcome in OUTCOMES:
            results[scope][outcome] = _run_contrast(
                scoped,
                outcome=outcome,
                output_prefix=output_prefix,
                scope=scope,
                config=config,
                training_frame=training_scopes.get(scope),
            )

    gate = _build_gate(results, panel=panel, family_spec=family_spec)
    action = panel["action"].astype(str)
    terminal = pd.to_numeric(panel["terminal_inventory_lifecycle_pnl"], errors="coerce")
    logged_tail = {
        name: {
            "rows": int(action.eq(name).sum()),
            "tail_5usdc_events": int((action.eq(name) & terminal.le(TAIL_THRESHOLD_USDC)).sum()),
            "terminal_mean": float(terminal[action.eq(name)].mean()),
            "terminal_q10": float(terminal[action.eq(name)].quantile(0.10)),
        }
        for name in (BASELINE_ACTION, CANDIDATE_ACTION)
    }
    summary = {
        "schema_version": SCHEMA_VERSION,
        "family_id": family_id,
        "side": side,
        "panel_role": args.panel_role,
        "panel_path": str(panel_path),
        "panel_sha256": _sha256(panel_path),
        "panel_metadata_path": str(metadata_path),
        "panel_metadata_sha256": _sha256(metadata_path),
        "development_panel_path": str(args.development_panel.expanduser().resolve()) if args.development_panel else "",
        "development_metadata_path": str(training_metadata_path or ""),
        "frozen_policy_path": str(policy_path or ""),
        "development_q10_usdc": q10,
        "candidate_policy": (
            "continue_block_until_recovery iff frozen four-path recovery "
            "score is below threshold; release on the recovery event"
            if family_spec is not None
            else "continue_block_until_recovery iff entry_state_active else baseline_rearm"
        ),
        "outcomes": list(OUTCOMES),
        "features": list(FEATURES),
        "logged_tail": logged_tail,
        "gate": gate,
        "results": {
            scope: {
                outcome: row["summary"]
                for outcome, row in outcome_rows.items()
            }
            for scope, outcome_rows in results.items()
        },
        "workspace": git_workspace_identity(ROOT),
        "promotion_status": (
            "eligible_to_open_next_panel"
            if gate["passed"]
            else "closed_at_current_panel"
        ),
    }
    summary_path = output_prefix.with_suffix(".summary.json")
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    scorecard_path: Path | None = None
    scorecard: dict[str, Any] | None = None
    if family_spec is not None and family_spec_path is not None:
        scorecard_path, scorecard = _write_scorecard(
            family_id=family_id,
            family_spec_path=family_spec_path,
            family_spec=family_spec,
            panel_role=args.panel_role,
            panel_path=panel_path,
            gate=gate,
            results=results,
            output_prefix=output_prefix,
        )
        summary["scorecard_path"] = str(scorecard_path)
        summary["scorecard_sha256"] = _sha256(scorecard_path)
        summary["scorecard_ranking_eligible"] = bool(
            scorecard["ranking_eligible"]
        )
        summary["promotion_status"] = str(scorecard["promotion_status"])
        summary_path.write_text(
            json.dumps(summary, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    if args.panel_role == "development":
        policy = {
            "schema_version": "state_conditioned_rearm_policy.v1",
            "family_id": family_id,
            "side": side,
            "status": "frozen_after_development_evaluation",
            "development_gate_passed": bool(gate["passed"]),
            "development_panel_path": str(panel_path),
            "development_panel_sha256": _sha256(panel_path),
            "development_summary_path": str(summary_path),
            "development_summary_sha256": _sha256(summary_path),
            "development_q10_usdc": q10,
            "candidate_action": CANDIDATE_ACTION,
            "baseline_action": BASELINE_ACTION,
            "candidate_rule": "entry_state_active",
            "state_spec": (
                dict(family_spec.get("recovery_event") or {})
                if family_spec is not None
                else asdict(StateConditionedRearmSpec())
            ),
            "features": list(FEATURES),
            "ope_config": vars(config),
        }
        policy_path = output_prefix.with_suffix(".frozen_policy.json")
        policy_path.write_text(json.dumps(policy, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(
        json.dumps(
            {
                "summary": str(summary_path),
                "policy": str(policy_path or ""),
                "scorecard": str(scorecard_path or ""),
                "gate_passed": gate["passed"],
                "ranking_eligible": bool(
                    scorecard["ranking_eligible"] if scorecard else False
                ),
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
