"""Export the deps-only legacy installation surface from pyproject.toml."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXTRAS = ("data", "research", "live", "provider-cryptohft")


def render_requirements(project: dict) -> str:
    dependencies = set(project["dependencies"])
    for extra in EXTRAS:
        dependencies.update(project["optional-dependencies"][extra])
    return (
        "# Generated by scripts/export_compat_requirements.py; edit pyproject.toml only.\n"
        "# Legacy deps-only base + data,research,live,provider-cryptohft; no dev/studio.\n"
        "# Installing provider clients grants no access, license or research eligibility.\n"
        + "\n".join(sorted(dependencies))
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without changing files")
    args = parser.parse_args()
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    rendered = render_requirements(project)
    if args.check:
        if (ROOT / "requirements.txt").read_text(encoding="utf-8") != rendered:
            print("requirements.txt is stale; regenerate from pyproject.toml", file=sys.stderr)
            return 1
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
